package docgenerator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/lucasassuncao/yedit/schema"
	"github.com/lucasassuncao/yedit/spec"
)

// mdRenderer holds everything the markdown rendering functions read. It is built
// per entry by emitMarkdown.
type mdRenderer struct {
	metadata       spec.MetadataSource
	examplesRelDir string
	examplePages   map[string]bool
}

// fieldMeta resolves metadata for a field within sectionPath.
func (g *mdRenderer) fieldMeta(sectionPath []string, fieldName string) spec.FieldMeta {
	return fieldMetaFor(g.metadata, sectionPath, fieldName)
}

// emitMarkdown writes one reference page per entry, plus one per split child.
func emitMarkdown(cfg *config, ctxs []entryCtx) ([]GeneratedFile, error) {
	var files []GeneratedFile
	written := map[string]bool{}
	for _, c := range ctxs {
		dir := cfg.markdownDirFor(c.entry)
		if err := os.MkdirAll(dir, 0750); err != nil {
			return nil, fmt.Errorf("create markdown dir: %w", err)
		}
		relDir, pages := cfg.exampleLinks(dir)
		g := &mdRenderer{metadata: c.meta, examplesRelDir: relDir, examplePages: pages}

		if !c.entry.SplitStructs {
			f, err := writeMarkdownOnce(written, dir, c.name, g.generateMarkdown(c.name, c.fields, nil))
			if err != nil {
				return nil, err
			}
			files = append(files, f)
			continue
		}

		f, err := writeMarkdownOnce(written, dir, c.name, g.generateRootMarkdown(c.name, c.fields))
		if err != nil {
			return nil, err
		}
		files = append(files, f)

		for _, fd := range c.fields {
			if fd.YAMLName == "" || fd.YAMLName == "-" || len(fd.Children) == 0 {
				continue
			}
			md := g.generateMarkdown(fd.YAMLName, fd.Children, []string{fd.YAMLName})
			child, err := writeMarkdownOnce(written, dir, fd.YAMLName, md)
			if err != nil {
				return nil, err
			}
			files = append(files, child)
		}
	}
	return files, nil
}

// writeMarkdownOnce errors when the same output file was already written in this
// run: two entries with a same-named page would otherwise silently overwrite
// each other.
func writeMarkdownOnce(written map[string]bool, dir, name, md string) (GeneratedFile, error) {
	path := filepath.Join(filepath.Clean(dir), strings.ToLower(name)+".md")
	if written[path] {
		return GeneratedFile{}, fmt.Errorf("duplicate docs page %q: %s was already generated by an earlier entry", name, path)
	}
	written[path] = true

	valid, ok := validatePathWithinBase(dir, path)
	if !ok {
		return GeneratedFile{}, fmt.Errorf("invalid docs path: %s", path)
	}
	if err := os.WriteFile(valid, []byte(md), 0600); err != nil {
		return GeneratedFile{}, fmt.Errorf("write docs page %s: %w", valid, err)
	}
	return GeneratedFile{Name: name, Path: valid}, nil
}

// generateRootMarkdown builds the summary page for a split root type: it links
// to per-field files instead of inlining nested sections.
func (g *mdRenderer) generateRootMarkdown(title string, fields []schema.FieldDef) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# %s\n\n", title)
	g.writeExamplesLink(&sb, title)
	sb.WriteString("## Arguments\n\n")
	sb.WriteString("The following arguments are supported:\n\n")
	g.writeFieldsTableLinked(&sb, fields)
	return sb.String()
}

func (g *mdRenderer) writeFieldsTableLinked(sb *strings.Builder, fields []schema.FieldDef) {
	hasFormat := g.anyHasFormat(fields, nil)
	if hasFormat {
		sb.WriteString("| Name | Type | Format | Description | Required | Default |\n")
		sb.WriteString("|------|------|--------|-------------|----------|---------|\n")
	} else {
		sb.WriteString("| Name | Type | Description | Required | Default |\n")
		sb.WriteString("|------|------|-------------|----------|---------|\n")
	}
	for _, f := range fields {
		name := f.YAMLName
		if name == "" || name == "-" {
			continue
		}
		meta := g.fieldMeta(nil, name)
		description := cellText(meta.Description)
		required := "No"
		if meta.Required {
			required = "Yes"
		}
		defaultValue := "-"
		if meta.Default != "" {
			defaultValue = cellText(meta.Default)
		}
		displayName := cellText(name)
		if len(f.Children) > 0 {
			displayName = fmt.Sprintf("[%s](./%s.md)", cellText(name), strings.ToLower(name))
		}
		if hasFormat {
			fmt.Fprintf(sb, "| %s | %s | %s | %s | %s | %s |\n",
				displayName, cellText(docTypeLabel(f, meta)), formatLabels(meta), description, required, defaultValue)
		} else {
			fmt.Fprintf(sb, "| %s | %s | %s | %s | %s |\n",
				displayName, cellText(docTypeLabel(f, meta)), description, required, defaultValue)
		}
	}
	sb.WriteString("\n")
}

// cellText collapses whitespace (including newlines) and escapes pipes so an
// interpolated value cannot break a markdown table row.
func cellText(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return strings.Join(strings.Fields(s), " ")
}

func (g *mdRenderer) generateMarkdown(typeName string, fields []schema.FieldDef, sectionPath []string) string {
	var sb strings.Builder

	fmt.Fprintf(&sb, "# %s\n\n", typeName)
	g.writeExamplesLink(&sb, typeName)
	sb.WriteString("## Arguments\n\n")
	sb.WriteString("The following arguments are supported:\n\n")
	g.writeFieldsTable(&sb, fields, sectionPath)
	g.writeNestedSections(&sb, fields, sectionPath, 3)

	return sb.String()
}

// writeExamplesLink emits an "Examples" section when WithExamples was set and an
// example page exists for title. The lookup is by lowercased title so root and
// split-child pages alike resolve to "<title>.md" in the examples directory.
func (g *mdRenderer) writeExamplesLink(sb *strings.Builder, title string) {
	if g.examplesRelDir == "" {
		return
	}
	key := strings.ToLower(title)
	if !g.examplePages[key] {
		return
	}
	sb.WriteString("## Examples\n\n")
	fmt.Fprintf(sb, "For usage examples, see [%s presets](%s/%s.md).\n\n", title, g.examplesRelDir, key)
}

func (g *mdRenderer) writeFieldsTable(sb *strings.Builder, fields []schema.FieldDef, sectionPath []string) {
	hasFormat := g.anyHasFormat(fields, sectionPath)
	if hasFormat {
		sb.WriteString("| Name | Type | Format | Description | Required | Default |\n")
		sb.WriteString("|------|------|--------|-------------|----------|---------|\n")
	} else {
		sb.WriteString("| Name | Type | Description | Required | Default |\n")
		sb.WriteString("|------|------|-------------|----------|---------|\n")
	}

	for _, f := range fields {
		name := f.YAMLName
		if name == "" || name == "-" {
			continue
		}

		meta := g.fieldMeta(sectionPath, name)

		description := cellText(meta.Description)

		required := "No"
		if meta.Required {
			required = "Yes"
		}

		defaultValue := "-"
		if meta.Default != "" {
			defaultValue = cellText(meta.Default)
		}

		displayName := cellText(name)

		if hasFormat {
			fmt.Fprintf(sb, "| %s | %s | %s | %s | %s | %s |\n",
				displayName, cellText(docTypeLabel(f, meta)), formatLabels(meta), description, required, defaultValue)
		} else {
			fmt.Fprintf(sb, "| %s | %s | %s | %s | %s |\n",
				displayName, cellText(docTypeLabel(f, meta)), description, required, defaultValue)
		}
	}
	sb.WriteString("\n")
}

func (g *mdRenderer) writeNestedSections(sb *strings.Builder, fields []schema.FieldDef, sectionPath []string, level int) {
	hashes := strings.Repeat("#", level)

	for _, f := range fields {
		if len(f.Children) == 0 {
			continue
		}
		name := f.YAMLName
		childPath := append(append([]string(nil), sectionPath...), name)

		fmt.Fprintf(sb, "%s %s\n\n", hashes, name)
		sb.WriteString("The following arguments are supported:\n\n")
		g.writeFieldsTable(sb, f.Children, childPath)
		g.writeNestedSections(sb, f.Children, childPath, level+1)
	}
}

// anyHasFormat reports whether any field carries formats, which decides if the
// table gets a Format column.
func (g *mdRenderer) anyHasFormat(fields []schema.FieldDef, sectionPath []string) bool {
	for _, f := range fields {
		name := f.YAMLName
		if name == "" || name == "-" {
			continue
		}
		meta := g.fieldMeta(sectionPath, name)
		if len(meta.Formats) > 0 {
			return true
		}
	}
	return false
}

// formatLabels joins the field's format labels, or "-" when none. Labels are
// pipe-escaped so they cannot split the table row into extra columns.
func formatLabels(meta spec.FieldMeta) string {
	var labels []string
	for _, f := range meta.Formats {
		if !f.IsZero() {
			labels = append(labels, cellText(f.Label()))
		}
	}
	if len(labels) == 0 {
		return "-"
	}
	return strings.Join(labels, ", ")
}

// docTypeLabel returns the table type label, honouring the FieldMeta.Multiline
// and FieldMeta.Type overrides.
func docTypeLabel(f schema.FieldDef, meta spec.FieldMeta) string {
	if meta.Multiline && meta.Type == "" {
		return "multiline string"
	}
	if meta.Type != "" {
		return meta.Type
	}
	return typeLabel(f)
}

func typeLabel(f schema.FieldDef) string {
	switch f.Kind {
	case schema.KindPrimitive:
		if f.Scalar != "" {
			return f.Scalar
		}
		return "any"
	case schema.KindObject, schema.KindVariant:
		return "object"
	case schema.KindList:
		if len(f.Children) > 0 {
			return "array[object]"
		}
		if f.Scalar != "" {
			return "array[" + f.Scalar + "]"
		}
		return "array"
	case schema.KindDictionary:
		if len(f.Children) > 0 {
			return "map[string]object"
		}
		if f.Scalar != "" {
			return "map[string]" + f.Scalar
		}
		return "map"
	case schema.KindAny:
		return "any"
	default:
		return "-"
	}
}
